version: 2
jobs:
   build:
     docker:
       - image: circleci/node:7.10
     steps:
       - checkout
       - run: echo "hello world"
       - deploy:
           name: Simple Deploy
           command: |
             if [ "${CIRCLE_BRANCH}" == "master" ]; then
               ./deploy_prod.sh
             fi